name: 'Setup Rust Environment'
description: 'Installs Rust, caches Cargo dependencies, and optionally installs mise tools'
inputs:
  rust-version:
    description: 'Rust toolchain version'
    required: false
    default: 'stable'
  components:
    description: 'Rust toolchain components to install (comma-separated, e.g., rustfmt,clippy)'
    required: false
    default: ''
  install-mise:
    description: 'Install mise and optional tools'
    required: false
    default: 'false'
  mise-version:
    description: 'mise version to install'
    required: false
    default: '2026.2.19'
  mise-tools:
    description: 'mise install arguments (space-separated, e.g., cargo:cargo-tarpaulin actionlint)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}
        components: ${{ inputs.components }}

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Normalize mise install args
      if: inputs.install-mise == 'true'
      id: setup-mise-args
      shell: bash
      run: |
        set -euo pipefail
        normalized="$(printf '%s' "${{ inputs.mise-tools }}" | tr -s '[:space:]' ' ' | sed 's/^ //;s/ $//')"
        echo "install_args=${normalized}" >> "${GITHUB_OUTPUT}"

    - name: Setup mise
      if: inputs.install-mise == 'true'
      uses: jdx/mise-action@v3
      with:
        version: ${{ inputs.mise-version }}
        install_args: ${{ steps.setup-mise-args.outputs.install_args }}
