name: 'Install jlo'
description: 'Installs the jlo CLI binary pinned to .jules/.jlo-version on the jules branch'
inputs:
  enforce-checksums:
    description: 'Fail if checksum verification is not possible'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install jlo
      shell: bash
      run: |
        set -euo pipefail
        : "${GITHUB_PATH:?GITHUB_PATH must be set}"

        if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
          echo "::error::install-jlo must run inside a git repository."
          exit 1
        fi

        if ! git remote get-url origin >/dev/null 2>&1; then
          echo "::error::origin remote not found; cannot fetch jules branch."
          exit 1
        fi

        echo "Fetching origin/jules..."
        if ! git fetch --quiet --depth=1 origin jules; then
          echo "::error::jules branch does not exist on origin."
          exit 1
        fi

        JULES_REF="origin/jules"

        VERSION_RAW="$(git show "${JULES_REF}:.jules/.jlo-version" 2>/dev/null | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        if [ -z "$VERSION_RAW" ]; then
          echo "::error::.jules/.jlo-version is missing or empty on '${JULES_REF}'."
          exit 1
        fi

        VERSION="${VERSION_RAW#v}"
        TAG_VERSION="v${VERSION}"

        if command -v jlo >/dev/null 2>&1; then
          INSTALLED_VERSION="$(jlo --version 2>/dev/null | tr -d '\r' | grep -o -E '[0-9]+\\.[0-9]+\\.[0-9]+' | head -n 1 || true)"
          if [ -n "$INSTALLED_VERSION" ] && [ "$INSTALLED_VERSION" = "$VERSION" ]; then
            echo "✅ jlo ${VERSION} already installed; skipping download."
            exit 0
          fi
          if [ -n "$INSTALLED_VERSION" ]; then
            echo "Existing jlo ${INSTALLED_VERSION} does not match expected ${VERSION}; reinstalling."
          else
            echo "Existing jlo found but version could not be determined; reinstalling expected ${VERSION}."
          fi
        fi

        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        case "$OS" in
          linux) OS="linux" ;;
          darwin) OS="darwin" ;;
          *)
            echo "::error::Unsupported OS for jlo install: $OS"
            exit 1
            ;;
        esac

        case "$ARCH" in
          x86_64|amd64) ARCH="x86_64" ;;
          arm64|aarch64) ARCH="aarch64" ;;
          *)
            echo "::error::Unsupported architecture for jlo install: $ARCH"
            exit 1
            ;;
        esac

        ASSET="jlo-${OS}-${ARCH}"
        URL="https://github.com/akitorahayashi/jlo/releases/download/${TAG_VERSION}/${ASSET}"

        TEMP_DIR=$(mktemp -d)
        cd "$TEMP_DIR"

        echo "Installing jlo ${VERSION} from: $URL"
        curl --fail --silent --show-error --location \
          --connect-timeout 10 \
          --max-time 60 \
          --retry 3 \
          --retry-delay 2 \
          --retry-all-errors \
          "$URL" -o "$ASSET"

        CHECKSUM_FILES="checksums.txt SHA256SUMS"
        VERIFIED=0

        for CS_FILE in $CHECKSUM_FILES; do
          CS_URL="https://github.com/akitorahayashi/jlo/releases/download/${TAG_VERSION}/${CS_FILE}"
          echo "Attempting to fetch checksums from $CS_URL"
          if curl --fail --silent --show-error --location "$CS_URL" -o "$CS_FILE"; then
            echo "Found $CS_FILE. Verifying..."
            # Use strict matching: verify asset name appears at end of line
            if grep -E "  ${ASSET}$" "$CS_FILE" > "${ASSET}.sha256"; then
              if command -v sha256sum >/dev/null 2>&1; then
                sha256sum -c "${ASSET}.sha256"
              elif command -v shasum >/dev/null 2>&1; then
                shasum -a 256 -c "${ASSET}.sha256"
              else
                echo "::error::Missing sha256sum/shasum tool."
                exit 1
              fi
              VERIFIED=1
              break
            else
              echo "::warning::$ASSET not found in $CS_FILE"
            fi
          fi
        done

        if [ "$VERIFIED" -ne 1 ]; then
          if [ "${{ inputs.enforce-checksums }}" = "true" ]; then
            echo "::error::Checksum verification failed or not possible, and enforce-checksums is true."
            exit 1
          else
            echo "::warning::Could not verify checksum. No checksum file found or asset not listed. Proceeding without verification."
          fi
        fi

        mv "$ASSET" jlo
        chmod +x jlo

        INSTALL_DIR="${RUNNER_TEMP:-/tmp}/jlo-bin"
        mkdir -p "$INSTALL_DIR"
        mv jlo "$INSTALL_DIR/jlo"

        cd - >/dev/null
        rm -rf "$TEMP_DIR"

        echo "$INSTALL_DIR" >> "$GITHUB_PATH"
        echo "✅ jlo installed: $($INSTALL_DIR/jlo --version 2>/dev/null || echo 'version unknown')"
