name: 'Run Implementer'
description: 'Run an implementer for a single issue and clean up related events'
inputs:
  issue_file:
    description: 'Issue file path'
    required: true
  dry_run:
    description: 'Show prompts without executing'
    required: false
    default: 'false'
  jlo_version:
    description: 'jlo version to install'
    required: false
    default: 'latest'
  target_branch:
    description: 'Target branch for implementer output'
    required: false
    default: 'main'
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      env:
        ISSUE_FILE: ${{ inputs.issue_file }}
      run: |
        if [ -z "$ISSUE_FILE" ]; then
          echo "::error::issue_file is required"
          exit 1
        fi
        if [ ! -f "$ISSUE_FILE" ]; then
          echo "::error::Issue file not found in repository: $ISSUE_FILE"
          exit 1
        fi

    - name: Install jlo
      uses: ./.github/actions/install-jlo
      with:
        version: ${{ inputs.jlo_version }}

    - name: Run implementers
      shell: bash
      env:
        ISSUE_FILE: ${{ inputs.issue_file }}
        DRY_RUN: ${{ inputs.dry_run }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
      run: |
        args=("$ISSUE_FILE")
        [ "$DRY_RUN" = "true" ] && args+=("--dry-run")
        jlo run implementers "${args[@]}" --branch "$TARGET_BRANCH"

    - name: Configure Git
      if: ${{ inputs.dry_run != 'true' }}
      uses: ./.github/actions/configure-git

    - name: Delete processed issue and source events
      if: ${{ inputs.dry_run != 'true' }}
      shell: bash
      env:
        ISSUE_FILE: ${{ inputs.issue_file }}
      run: bash .github/scripts/jules-delete-processed-issue-and-events.sh
